### PR TITLE
Fix/fetch race condition

### LINKED ISSUE #1396: Multiple Name Appearing in Boards
**Describe the bug**
Multiple Name Appearing in Boards.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on Create Board
2. Give the details. (Name, Color code)
3. Click on save
4. Clicked on Dashboard
5. Then again click on Board.

**Expected behaviour**
Expected only 1 name to be displayed.

**Screenshots**

Image

**Desktop (please complete the following information):**
 - LogChimp [e.g. v0.7.0]
 - OS: [e.g. Windows 11]
 - Browser [e.g. Edge]
 - Browser version [e.g. 141.0.3537.71 ]

### PR DESCRIPTION
**Pull request by Ja4V8s28Ck**
Fixes #1396

Handles the race condition where `boards/posts/roles` are fetched multiple times due to network or resource constraints.

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented duplicate or overlapping loads when viewing boards, reducing repeated results and flicker.
  * Prevented redundant role lookups during rapid interactions, improving stability.
  * Fixed infinite-scroll “Load more” to stop extra fetches once loading or completed, making scrolling smoother and more reliable.

### CODE REVIEW

**Comment by Ja4V8s28Ck** [comment]
@mittalyashu Can you check if the issue still exists?

**Comment by mittalyashu** [comment]
the fix works.

File: packages/theme/src/ee/store/dashboard/roles.ts [hunk 1]
```diff
@@ -14,6 +14,10 @@ export const useDashboardRoles = defineStore("dashboardRoles", () => {
   const error = ref<unknown>(undefined);
 
   async function fetchRoles() {
+    if (state.value === "LOADING" || state.value === "COMPLETED") {
+      return;
+    }
```
Comment (mittalyashu) [inline packages/theme/src/ee/store/dashboard/roles.ts]: Can you make this if statement, one-liner for now?

File: packages/theme/src/ee/store/dashboard/boards.ts [hunk 2]
```diff
@@ -14,6 +14,10 @@ export const useDashboardBoards = defineStore("dashboardBoards", () => {
   const page = ref<number>(1);
 
   async function fetchBoards() {
+    if (state.value === "LOADING" || state.value === "COMPLETED") {
+      return;
+    }
```
Comment (mittalyashu) [inline packages/theme/src/ee/store/dashboard/boards.ts]: Can you make this if statement, one-liner for now?

File: packages/theme/src/pages/boards/Index.vue [hunk 3]
```diff
@@ -42,6 +42,12 @@ const state = ref<InfiniteScrollStateType>();
 
 async function getBoards() {
   try {
+    if (state.value === "LOADING" || state.value === "COMPLETED") {
+      return;
+    }
```
Comment (mittalyashu) [inline packages/theme/src/pages/boards/Index.vue]: Can you make this if statement, one-liner for now?

File: packages/theme/src/pages/Index.vue [hunk 4]
```diff
@@ -55,6 +55,10 @@ async function isSetup() {
 }
 
 async function loadMorePosts() {
+  if (state.value === "LOADING" || state.value === "COMPLETED") {
+    return;
+  }
```
Comment (mittalyashu) [inline packages/theme/src/pages/Index.vue]: Can you make this if statement, one-liner for now?

**Comment by mittalyashu** [comment]
LGTM
