### PR TITLE
fix: Create unique username with nanoid to avoid violation of unique constraint "users_username_unique"

### LINKED ISSUE #1319: Handle `duplicate key value violates unique constraint "users_username_unique"` durning signup
**Steps to reproduce**

1. Signup with email `new1@example.com`
2. _logout_
3. Signup with email `new1@e.com`

### PR DESCRIPTION
**Pull request by Vedant005**
Fixes #1319 

Used nanid and already existing helper function to create unique username

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved username generation during registration: usernames are now based on the email prefix, automatically truncated as needed and given a short unique suffix to ensure uniqueness and avoid conflicts.
  * Updated tests to stop asserting exact username values and instead validate account email and status.

### CODE REVIEW

File: packages/server/src/services/auth/createUser.ts [hunk 1]
```diff
@@ -149,3 +157,16 @@ const createUser = async (
 };
 
 export { createUser };
+
+async function generateUniqueUsername(baseUsername: string): Promise<string> {
+  let username = baseUsername;
+  let exists = await database("users").where({ username }).first();
+
+  while (exists) {
```
Comment (mittalyashu) [inline packages/server/src/services/auth/createUser.ts]: Using `while` loop, is a big no go.

Loop can trigger multiple sequential database queries.

---

Check with nanoid docs at how much length the random string has the change to get repeated and accordingly try to increase/decease the char length of random string.

Comment (mittalyashu) [reply packages/server/src/services/auth/createUser.ts]: @coderabbitai anything you would like to share?

File: packages/server/src/services/auth/createUser.ts [hunk 2]
```diff
@@ -51,7 +55,9 @@ const createUser = async (
   const name = sanitiseName(userData.name);
 
   // get username from email address after truncating to first 30 characters and sanitise
-  const username = sanitiseUsername(userData.email.split("@")[0].slice(0, 30));
+  const baseUsername = sanitiseUsername(
+    userData.email.split("@")[0].slice(0, 30),
+  );
```
Comment (mittalyashu) [inline packages/server/src/services/auth/createUser.ts:60]: > This is rough idea, you can further improve it to handle any edge-cases.

@Vedant005 What's your take on this approach? 👇

You directly pass the split-ed raw username to the function.

And based on the length of the `baseUsername`, if length >= 22 then we get the first 21 char of base username and append with `_{nanoid}`, else `{username}_{nanoid}`.

---

The reason because as per your current implementation in `generateUniqueUsername` function you slice the username after append the nanoid.

File: packages/server/src/services/auth/createUser.ts [hunk 3]
```diff
@@ -149,3 +157,12 @@ const createUser = async (
 };
 
 export { createUser };
+
+function generateUniqueUsername(baseUsername: string): string {
+  let username = baseUsername;
+
+  const suffix = nanoid(8);
+  username = `${baseUsername}-${suffix}`.slice(0, 30);
```
Comment (mittalyashu) [inline packages/server/src/services/auth/createUser.ts]: Can you double-check? I think we don't support `-` in the username as per `sanitiseUsername` function.

**Review by mittalyashu — CHANGES_REQUESTED** [review]

**Comment by mittalyashu** [comment]
~~Alright, let me continue with this PR to move faster 🙂~~

**Comment by Vedant005** [comment]
> Alright, let me continue with this PR to move faster 🙂

I was working on this now. I'll work on other ones then

**Comment by mittalyashu** [comment]
> > Alright, let me continue with this PR to move faster 🙂
> 
> I was working on this now. I'll work on other ones then

If you're working on it, you can continue working on it. 🙂

File: packages/server/src/services/auth/createUser.ts (hunk 3 above)
Comment (Vedant005) [reply packages/server/src/services/auth/createUser.ts]: Well, it creates username with `-`

`Joe-n9j4c0fh`

Comment (Vedant005) [reply packages/server/src/services/auth/createUser.ts]: I'll fix it

File: packages/server/src/services/auth/createUser.ts [hunk 4]
```diff
@@ -149,3 +157,18 @@ const createUser = async (
...
+  let trimmedBase: string;
+
+  if (baseUsername.length >= 22) {
+    trimmedBase = baseUsername.slice(0, 21);
+  } else {
+    trimmedBase = baseUsername;
+  }
+
+  return `${trimmedBase}${separator}${suffix}`;
+}
```
[the remark this answers is not in the document]
Comment (Vedant005) [reply packages/server/src/services/auth/createUser.ts:174]: @mittalyashu

**Comment by Vedant005** [comment]
@mittalyashu  made changes. Check if proper

File: packages/server/src/services/auth/createUser.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (mittalyashu) [reply packages/server/src/services/auth/createUser.ts:174]: [This PR](https://github.com/logchimp/logchimp/pull/1494) should handle this case by further decreasing the probability of conflicting username in the database.
